version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - skomma
  ignore:
  - dependency-name: jenkins/jenkins
    versions:
    - ">= 2.184.pre.slim.a, < 2.185"
  - dependency-name: jenkins/jenkins
    versions:
    - 2.276.pre.slim
    - 2.277.pre.slim
    - 2.279.pre.slim
    - 2.280.pre.slim
    - 2.281.pre.slim
    - 2.282.pre.slim
    - 2.283.pre.slim
    - 2.284.pre.slim
    - 2.285.pre.slim
    - 2.286.pre.slim
    - 2.287.pre.slim
    - 2.288.pre.slim
